#for build image
#docker build -t <name_image>:<tag_image> .

#for run container 
# docker run -d -rm --name <name_container> --publish=<numper_port_local>:<number_port_container> <name_image>:<tag_image>
FROM ubuntu:18.04
LABEL maintainer="prive_s@ukr.net"
RUN apt-get -y update \
&& apt-get -y install php-cli \
&& apt-get -y install php-common \
&& apt-get -y install php-mysql \
&& apt-get clean \
&& rm -rf /tmp/* \
&& rm -rf /var/lib/apt/lists/*
ENTRYPOINT ["php", "/project/reactPhpForDocker.php"]